version: 0.2
os: linux
files:
  - source: /addressbook.war
    destination: /usr/share/tomcat/webapps
permissions:
  - object: /usr/share/tomcat/webapps
    pattern: '**'
    mode: '0775'
    owner: root
    group: root
    type:
      - file
      - directory
hooks:
   ApplicationStart:
    - location: /app.sh
      timeout: 300
